services:
  mysql:
    image: mysql:8.0
    container_name: mysql-labscheduler
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: labscheduler
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - labscheduler-data:/var/lib/mysql
      - ./labscheduler_backups:/backup
    networks:
      - labscheduler-network
    restart: always
  memcached:
    image: memcached:1.6
    container_name: memcached-labscheduler
    ports:
      - "11211:11211"
    networks:
      - labscheduler-network
    restart: always
  server:
    build: .   # build from Dockerfile
    container_name: labscheduler-server
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/labscheduler
      - DB_USERNAME=root
      - DB_PASSWORD=123
      - MEMCACHED_HOST=memcached
      - MAIL_USERNAME=hocongtoan987@gmail.com
      - MAIL_PASSWORD=ouijkdlyogbndrac
    networks:
      - labscheduler-network
  website:
    build: ../labscheduler-website
    container_name: labscheduler-website
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    networks:
      - labscheduler-network
    depends_on:
      - server

  mysql-backup:
    image: mysql:8.0
    container_name: mysql-backup-labscheduler
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: labscheduler-backup
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./labscheduler_backups:/backup
    networks:
      - labscheduler-network
    restart: always
volumes:
  labscheduler-data:

networks:
  labscheduler-network:
    driver: bridge

# docker-compose up --build -d