version: "3.8"

services:
  app:
    container_name: labscheduler-springboot-app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/labscheduler
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - labscheduler-network

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=labscheduler
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - labscheduler-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  labscheduler-network:
    driver: bridge
