spring:
  application:
    name: LabScheduler-Server

  datasource:
    url: jdbc:mysql://localhost:3306/labscheduler
    username: root
    password: "123"
    driver-class-name: com.mysql.cj.jdbc.Driver


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Mail server configuration
  # mail:
  #   host: smtp.gmail.com
  #   port: 587
  #   username:
  #   password:
  #   properties:
  #     mail.smtp.auth: true
  #     mail.smtp.starttls.enable: true
